// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: text_embosser/text_embosser.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - text_embosser.TextEmbosser

/// Namespace containing generated types for the "text_embosser.TextEmbosser" service.
public enum TextEmbosser_TextEmbosser {
    /// Service descriptor for the "text_embosser.TextEmbosser" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "text_embosser.TextEmbosser")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "EmbossText" metadata.
        public enum EmbossText {
            /// Request type for "EmbossText".
            public typealias Input = TextEmbosser_EmbossTextRequest
            /// Response type for "EmbossText".
            public typealias Output = TextEmbosser_EmbossTextResponse
            /// Descriptor for "EmbossText".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "text_embosser.TextEmbosser"),
                method: "EmbossText"
            )
        }
        /// Descriptors for all methods in the "text_embosser.TextEmbosser" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            EmbossText.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "text_embosser.TextEmbosser" service.
    public static let textEmbosser_TextEmbosser = GRPCCore.ServiceDescriptor(fullyQualifiedService: "text_embosser.TextEmbosser")
}

// MARK: text_embosser.TextEmbosser (server)

extension TextEmbosser_TextEmbosser {
    /// Streaming variant of the service protocol for the "text_embosser.TextEmbosser" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "EmbossText" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `TextEmbosser_EmbossTextRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `TextEmbosser_EmbossTextResponse` messages.
        func embossText(
            request: GRPCCore.StreamingServerRequest<TextEmbosser_EmbossTextRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<TextEmbosser_EmbossTextResponse>
    }

    /// Service protocol for the "text_embosser.TextEmbosser" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: TextEmbosser_TextEmbosser.StreamingServiceProtocol {
        /// Handle the "EmbossText" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `TextEmbosser_EmbossTextRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `TextEmbosser_EmbossTextResponse` message.
        func embossText(
            request: GRPCCore.ServerRequest<TextEmbosser_EmbossTextRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<TextEmbosser_EmbossTextResponse>
    }

    /// Simple service protocol for the "text_embosser.TextEmbosser" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: TextEmbosser_TextEmbosser.ServiceProtocol {
        /// Handle the "EmbossText" method.
        ///
        /// - Parameters:
        ///   - request: A `TextEmbosser_EmbossTextRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `TextEmbosser_EmbossTextResponse` to respond with.
        func embossText(
            request: TextEmbosser_EmbossTextRequest,
            context: GRPCCore.ServerContext
        ) async throws -> TextEmbosser_EmbossTextResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
extension TextEmbosser_TextEmbosser.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: TextEmbosser_TextEmbosser.Method.EmbossText.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<TextEmbosser_EmbossTextRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<TextEmbosser_EmbossTextResponse>(),
            handler: { request, context in
                try await self.embossText(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension TextEmbosser_TextEmbosser.ServiceProtocol {
    public func embossText(
        request: GRPCCore.StreamingServerRequest<TextEmbosser_EmbossTextRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<TextEmbosser_EmbossTextResponse> {
        let response = try await self.embossText(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension TextEmbosser_TextEmbosser.SimpleServiceProtocol {
    public func embossText(
        request: GRPCCore.ServerRequest<TextEmbosser_EmbossTextRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<TextEmbosser_EmbossTextResponse> {
        return GRPCCore.ServerResponse<TextEmbosser_EmbossTextResponse>(
            message: try await self.embossText(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: text_embosser.TextEmbosser (client)

extension TextEmbosser_TextEmbosser {
    /// Generated client protocol for the "text_embosser.TextEmbosser" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "EmbossText" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `TextEmbosser_EmbossTextRequest` message.
        ///   - serializer: A serializer for `TextEmbosser_EmbossTextRequest` messages.
        ///   - deserializer: A deserializer for `TextEmbosser_EmbossTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func embossText<Result>(
            request: GRPCCore.ClientRequest<TextEmbosser_EmbossTextRequest>,
            serializer: some GRPCCore.MessageSerializer<TextEmbosser_EmbossTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<TextEmbosser_EmbossTextResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<TextEmbosser_EmbossTextResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "text_embosser.TextEmbosser" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "EmbossText" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `TextEmbosser_EmbossTextRequest` message.
        ///   - serializer: A serializer for `TextEmbosser_EmbossTextRequest` messages.
        ///   - deserializer: A deserializer for `TextEmbosser_EmbossTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func embossText<Result>(
            request: GRPCCore.ClientRequest<TextEmbosser_EmbossTextRequest>,
            serializer: some GRPCCore.MessageSerializer<TextEmbosser_EmbossTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<TextEmbosser_EmbossTextResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<TextEmbosser_EmbossTextResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: TextEmbosser_TextEmbosser.Method.EmbossText.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension TextEmbosser_TextEmbosser.ClientProtocol {
    /// Call the "EmbossText" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `TextEmbosser_EmbossTextRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func embossText<Result>(
        request: GRPCCore.ClientRequest<TextEmbosser_EmbossTextRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<TextEmbosser_EmbossTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.embossText(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<TextEmbosser_EmbossTextRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<TextEmbosser_EmbossTextResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension TextEmbosser_TextEmbosser.ClientProtocol {
    /// Call the "EmbossText" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func embossText<Result>(
        _ message: TextEmbosser_EmbossTextRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<TextEmbosser_EmbossTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<TextEmbosser_EmbossTextRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.embossText(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}